import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F8F9FB',
  },
  startHeader: {
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 16,
    backgroundColor: '#FFFFFF',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  answerHeader: {
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 16,
    backgroundColor: '#FFFFFF',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerIconButton: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: '#F8F9FB',
    alignItems: 'center',
    justifyContent: 'center',
  },
  pageTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#1A1A2E',
  },
  helpText: {
    fontSize: 20,
    fontWeight: '600',
    color: '#1A1A2E',
  },
  startContent: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 18,
  },
  examHero: {
    position: 'relative',
    padding: 22,
    borderRadius: 28,
    overflow: 'hidden',
    marginBottom: 18,
    shadowColor: '#4F8EF7',
    shadowOffset: { width: 0, height: 16 },
    shadowOpacity: 0.26,
    shadowRadius: 36,
    elevation: 8,
  },
  heroHalo: {
    position: 'absolute',
    width: 150,
    height: 150,
    right: -56,
    top: -52,
    borderRadius: 75,
    backgroundColor: 'rgba(255, 255, 255, 0.16)',
  },
  examStatus: {
    alignSelf: 'flex-start',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 14,
    backgroundColor: 'rgba(255, 255, 255, 0.18)',
    fontSize: 11,
    fontWeight: '700',
    color: '#FFFFFF',
    letterSpacing: 0.4,
    marginBottom: 14,
  },
  examName: {
    fontSize: 24,
    lineHeight: 30,
    fontWeight: '800',
    color: '#FFFFFF',
    marginBottom: 10,
  },
  examDesc: {
    maxWidth: 280,
    fontSize: 13,
    lineHeight: 22,
    color: 'rgba(255, 255, 255, 0.86)',
  },
  summaryGrid: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 18,
  },
  summaryCard: {
    flex: 1,
    minHeight: 104,
    padding: 16,
    borderRadius: 20,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E8E8F0',
  },
  summaryIcon: {
    width: 34,
    height: 34,
    borderRadius: 12,
    backgroundColor: 'rgba(79, 142, 247, 0.12)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  summaryLabel: {
    fontSize: 12,
    color: '#8A8A9A',
    marginBottom: 4,
  },
  summaryValue: {
    fontSize: 18,
    lineHeight: 23,
    fontWeight: '800',
    color: '#1A1A2E',
  },
  sectionCard: {
    padding: 18,
    borderRadius: 24,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E8E8F0',
    marginBottom: 16,
  },
  sectionTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 14,
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: '#1A1A2E',
  },
  requirementItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    marginBottom: 12,
  },
  requirementIndex: {
    width: 22,
    height: 22,
    borderRadius: 8,
    backgroundColor: '#F8F9FB',
    color: '#4F8EF7',
    fontSize: 12,
    lineHeight: 22,
    fontWeight: '800',
    textAlign: 'center',
    overflow: 'hidden',
  },
  requirementText: {
    flex: 1,
    fontSize: 13,
    lineHeight: 20,
    color: '#4B5563',
    fontWeight: '500',
  },
  noticeCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    padding: 14,
    borderRadius: 18,
    backgroundColor: 'rgba(255, 176, 32, 0.08)',
    borderWidth: 1,
    borderColor: 'rgba(255, 176, 32, 0.2)',
    marginBottom: 12,
  },
  noticeIcon: {
    width: 20,
    height: 20,
    fontSize: 15,
    lineHeight: 20,
    fontWeight: '800',
    color: '#FFB020',
    textAlign: 'center',
  },
  noticeCopy: {
    flex: 1,
    fontSize: 12,
    lineHeight: 19,
    color: '#986F08',
    fontWeight: '600',
  },
  confirmRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingTop: 14,
    paddingHorizontal: 2,
    paddingBottom: 24,
  },
  confirmDot: {
    width: 18,
    height: 18,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
  },
  confirmText: {
    flex: 1,
    fontSize: 12,
    lineHeight: 18,
    color: '#8A8A9A',
  },
  timerPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(255, 90, 90, 0.15)',
    backgroundColor: 'rgba(255, 90, 90, 0.08)',
  },
  timerText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#FF5A5A',
    letterSpacing: 0.5,
  },
  progressPill: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 14,
    backgroundColor: '#F8F9FB',
  },
  progressText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#8A8A9A',
  },
  warningBanner: {
    marginHorizontal: 16,
    marginBottom: 16,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 176, 32, 0.18)',
    backgroundColor: 'rgba(255, 176, 32, 0.08)',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  warningIcon: {
    width: 18,
    fontSize: 16,
    lineHeight: 18,
    color: '#FFB020',
    fontWeight: '800',
    textAlign: 'center',
  },
  warningText: {
    flex: 1,
    fontSize: 11,
    lineHeight: 17,
    color: '#B8860B',
    fontWeight: '500',
  },
  submitErrorBanner: {
    marginHorizontal: 16,
    marginTop: -8,
    marginBottom: 16,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 90, 90, 0.18)',
    backgroundColor: 'rgba(255, 90, 90, 0.08)',
  },
  submitErrorText: {
    fontSize: 12,
    lineHeight: 18,
    color: '#D84343',
    fontWeight: '600',
  },
  answerContent: {
    flex: 1,
    paddingHorizontal: 20,
  },
  questionMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 16,
  },
  questionType: {
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 12,
  },
  questionTypeText: {
    fontSize: 11,
    lineHeight: 15,
    fontWeight: '700',
    color: '#FFFFFF',
    letterSpacing: 0.5,
  },
  questionScore: {
    fontSize: 12,
    color: '#8A8A9A',
    fontWeight: '500',
  },
  questionText: {
    fontSize: 18,
    fontWeight: '600',
    lineHeight: 29,
    color: '#1A1A2E',
    marginBottom: 28,
  },
  questionTextFill: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    marginBottom: 28,
  },
  questionTextFillChar: {
    fontSize: 18,
    fontWeight: '600',
    lineHeight: 32,
    color: '#1A1A2E',
  },
  blankMarkerTouchable: {
    width: 30,
    height: 30,
    marginHorizontal: 3,
    marginVertical: 1,
  },
  blankMarkerContainer: {
    width: 30,
    height: 30,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: 'rgba(79, 142, 247, 0.3)',
    backgroundColor: 'rgba(79, 142, 247, 0.08)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  blankMarkerText: {
    fontSize: 13,
    lineHeight: 16,
    fontWeight: '700',
    color: '#4F8EF7',
  },
  blankMarkerFilledText: {
    fontSize: 13,
    lineHeight: 16,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  blankMarkerFilledShadow: {
    borderWidth: 0,
    shadowColor: '#4F8EF7',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.22,
    shadowRadius: 16,
    elevation: 4,
  },
  options: {
    gap: 12,
    paddingBottom: 20,
  },
  option: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    padding: 16,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: '#E8E8F0',
    backgroundColor: '#FFFFFF',
  },
  optionSelected: {
    borderColor: '#4F8EF7',
    backgroundColor: 'rgba(79, 142, 247, 0.08)',
  },
  optionLetter: {
    width: 40,
    height: 40,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#4F8EF7',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 20,
    elevation: 5,
  },
  optionLetterIdle: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: '#F8F9FB',
    alignItems: 'center',
    justifyContent: 'center',
  },
  optionLetterText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#8A8A9A',
  },
  optionLetterSelectedText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  optionText: {
    flex: 1,
    fontSize: 14,
    lineHeight: 21,
    color: '#1A1A2E',
    fontWeight: '500',
  },
  optionSelectedText: {
    fontWeight: '600',
  },
  optionCheck: {
    width: 24,
    height: 24,
    alignItems: 'center',
    justifyContent: 'center',
    opacity: 0,
  },
  optionCheckSelected: {
    opacity: 1,
  },
  fillAnswerArea: {
    padding: 20,
    borderRadius: 20,
    backgroundColor: '#F8F9FB',
    marginBottom: 20,
  },
  fillAnswerTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 16,
  },
  fillAnswerTitle: {
    fontSize: 13,
    fontWeight: '600',
    color: '#8A8A9A',
  },
  fillBlankItem: {
    marginBottom: 16,
  },
  fillBlankItemLast: {
    marginBottom: 0,
  },
  fillBlankLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 8,
  },
  fillBlankIndex: {
    width: 24,
    height: 24,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  fillBlankIndexText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  fillBlankLabel: {
    fontSize: 13,
    fontWeight: '500',
    color: '#1A1A2E',
  },
  fillInputWrapper: {
    position: 'relative',
    borderRadius: 18,
  },
  fillInputWrapperFocused: {
    backgroundColor: 'rgba(79, 142, 247, 0.15)',
    padding: 4,
    margin: -4,
    borderRadius: 18,
  },
  fillInput: {
    minHeight: 52,
    paddingHorizontal: 16,
    paddingVertical: 14,
    paddingRight: 80,
    borderRadius: 14,
    borderWidth: 2,
    borderColor: '#E8E8F0',
    backgroundColor: '#FFFFFF',
    fontSize: 15,
    color: '#1A1A2E',
  },
  fillInputFocused: {
    borderColor: '#4F8EF7',
  },
  fillInputFilled: {
    borderColor: '#4F8EF7',
  },
  fillHint: {
    position: 'absolute',
    right: 12,
    top: 17,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  fillHintText: {
    fontSize: 12,
    color: '#8A8A9A',
  },
  bottomBar: {
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 24,
    backgroundColor: '#FFFFFF',
    borderTopWidth: 1,
    borderTopColor: '#E8E8F0',
    flexDirection: 'row',
    gap: 12,
  },
  secondaryButton: {
    flex: 1,
    height: 52,
    borderRadius: 16,
    backgroundColor: '#F8F9FB',
    alignItems: 'center',
    justifyContent: 'center',
  },
  secondaryButtonText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#8A8A9A',
  },
  primaryButtonWrap: {
    flex: 1,
    height: 52,
    borderRadius: 16,
    shadowColor: '#4F8EF7',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.35,
    shadowRadius: 24,
    elevation: 6,
  },
  primaryButton: {
    flex: 1,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  primaryButtonText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  disabledButton: {
    opacity: 0.5,
  },
  homeIndicator: {
    height: 8,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  homeIndicatorBar: {
    width: 134,
    height: 5,
    borderRadius: 100,
    backgroundColor: '#C8C7CC',
  },
  exitOverlay: {
    flex: 1,
    padding: 20,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  exitModal: {
    width: '100%',
    maxWidth: 335,
    paddingTop: 32,
    paddingHorizontal: 24,
    paddingBottom: 24,
    borderRadius: 28,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
  },
  exitIconWrap: {
    width: 80,
    height: 80,
    marginBottom: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  exitIconBg: {
    position: 'absolute',
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: 'rgba(79, 142, 247, 0.15)',
  },
  exitIcon: {
    width: 56,
    height: 56,
    borderRadius: 28,
    alignItems: 'center',
    justifyContent: 'center',
  },
  exitIconText: {
    fontSize: 28,
    lineHeight: 32,
    fontWeight: '800',
    color: '#FFFFFF',
  },
  exitTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: '#1A1A2E',
    marginBottom: 8,
  },
  exitDesc: {
    fontSize: 13,
    lineHeight: 20,
    color: '#8A8A9A',
    textAlign: 'center',
    marginBottom: 24,
  },
  exitButtons: {
    width: '100%',
    flexDirection: 'row',
    gap: 12,
  },
  exitContinueButton: {
    flex: 1,
    height: 48,
    borderRadius: 14,
    backgroundColor: '#F8F9FB',
    alignItems: 'center',
    justifyContent: 'center',
  },
  exitContinueText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#4F8EF7',
  },
  exitLeaveButton: {
    flex: 1,
    height: 48,
    borderRadius: 14,
    backgroundColor: '#1A1A2E',
    alignItems: 'center',
    justifyContent: 'center',
  },
  exitLeaveText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  loadingContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F8F9FB',
  },
  loadingText: {
    marginTop: 12,
    fontSize: 14,
    color: '#6B7280',
  },
});

export default styles;
