import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F8F9FB',
  },
  statusSpacer: {
    height: 30,
    backgroundColor: '#FFFFFF',
  },
  loadingContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  loadingText: {
    marginTop: 12,
    fontSize: 14,
    color: '#8A8A9A',
    fontWeight: '600',
  },
  header: {
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 14,
    backgroundColor: '#FFFFFF',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerIconButton: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: '#F8F9FB',
    alignItems: 'center',
    justifyContent: 'center',
  },
  pageTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: '#1A1A2E',
  },
  helpIcon: {
    fontSize: 19,
    lineHeight: 22,
    fontWeight: '800',
    color: '#1A1A2E',
  },
  toast: {
    position: 'absolute',
    top: 92,
    alignSelf: 'center',
    zIndex: 10,
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderRadius: 18,
    backgroundColor: 'rgba(26, 26, 46, 0.9)',
  },
  toastText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  content: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 18,
  },
  statusCard: {
    position: 'relative',
    borderRadius: 26,
    padding: 20,
    overflow: 'hidden',
    shadowColor: '#4F8EF7',
    shadowOffset: { width: 0, height: 16 },
    shadowOpacity: 0.26,
    shadowRadius: 34,
    elevation: 8,
  },
  statusHalo: {
    position: 'absolute',
    width: 132,
    height: 132,
    right: -50,
    top: -48,
    borderRadius: 66,
    backgroundColor: 'rgba(255, 255, 255, 0.14)',
  },
  statusPill: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 11,
    paddingVertical: 7,
    borderRadius: 18,
    backgroundColor: 'rgba(255, 255, 255, 0.18)',
    marginBottom: 15,
  },
  statusPillText: {
    fontSize: 12,
    fontWeight: '800',
    color: '#FFFFFF',
  },
  certificateName: {
    maxWidth: 270,
    fontSize: 21,
    lineHeight: 26,
    fontWeight: '800',
    color: '#FFFFFF',
    marginBottom: 8,
  },
  certificateDesc: {
    maxWidth: 270,
    fontSize: 13,
    lineHeight: 21,
    color: 'rgba(255, 255, 255, 0.92)',
  },
  certificateWrap: {
    marginTop: 14,
    padding: 14,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: '#E8E8F0',
    backgroundColor: '#FFFFFF',
  },
  certificateImageButton: {
    width: '100%',
    aspectRatio: 4 / 3,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(217, 164, 65, 0.38)',
    backgroundColor: '#FFF7E5',
    overflow: 'hidden',
  },
  certificateImage: {
    width: '100%',
    height: '100%',
  },
  previewHint: {
    marginTop: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  previewHintText: {
    fontSize: 12,
    color: '#8A8A9A',
    fontWeight: '700',
  },
  sectionCard: {
    marginTop: 14,
    padding: 18,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: '#E8E8F0',
    backgroundColor: '#FFFFFF',
  },
  noteCard: {
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#1A1A2E',
    marginBottom: 14,
  },
  infoList: {
    gap: 13,
  },
  infoRow: {
    paddingBottom: 13,
    borderBottomWidth: 1,
    borderBottomColor: '#E8E8F0',
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 16,
  },
  lastInfoRow: {
    paddingBottom: 0,
    borderBottomWidth: 0,
  },
  infoLabel: {
    flexShrink: 0,
    fontSize: 13,
    color: '#8A8A9A',
    fontWeight: '600',
  },
  infoValue: {
    flex: 1,
    textAlign: 'right',
    fontSize: 13,
    lineHeight: 18,
    color: '#1A1A2E',
    fontWeight: '800',
  },
  noteList: {
    gap: 10,
  },
  noteItem: {
    flexDirection: 'row',
    gap: 8,
  },
  noteBullet: {
    width: 10,
    fontSize: 13,
    lineHeight: 19,
    color: '#4F8EF7',
    fontWeight: '800',
  },
  noteText: {
    flex: 1,
    fontSize: 12,
    lineHeight: 19,
    color: '#8A8A9A',
    fontWeight: '600',
  },
  bottomBar: {
    paddingHorizontal: 20,
    paddingTop: 14,
    paddingBottom: 24,
    backgroundColor: '#FFFFFF',
    borderTopWidth: 1,
    borderTopColor: '#E8E8F0',
    flexDirection: 'row',
    gap: 12,
  },
  primaryButtonWrap: {
    flex: 1,
    height: 52,
    borderRadius: 16,
    shadowColor: '#4F8EF7',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.32,
    shadowRadius: 24,
    elevation: 6,
  },
  disabledButton: {
    opacity: 0.72,
  },
  primaryButton: {
    flex: 1,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 6,
  },
  primaryButtonText: {
    fontSize: 15,
    fontWeight: '800',
    color: '#FFFFFF',
  },
  secondaryButton: {
    flex: 1,
    height: 52,
    borderRadius: 16,
    backgroundColor: '#F8F9FB',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 6,
  },
  secondaryButtonText: {
    fontSize: 15,
    fontWeight: '800',
    color: '#1A1A2E',
  },
  homeIndicator: {
    height: 8,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  homeIndicatorBar: {
    width: 134,
    height: 5,
    borderRadius: 100,
    backgroundColor: '#C8C7CC',
  },
});

export default styles;
