import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F8F9FB',
  },
  loadingContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  loadingText: {
    marginTop: 12,
    fontSize: 14,
    color: '#8A8A9A',
    fontWeight: '600',
  },
  header: {
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 14,
    backgroundColor: '#FFFFFF',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerIconButton: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: '#F8F9FB',
    alignItems: 'center',
    justifyContent: 'center',
  },
  pageTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: '#1A1A2E',
  },
  toast: {
    position: 'absolute',
    top: 92,
    alignSelf: 'center',
    zIndex: 10,
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderRadius: 18,
    backgroundColor: 'rgba(26, 26, 46, 0.9)',
  },
  toastText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  content: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 18,
  },
  resultHero: {
    position: 'relative',
    paddingHorizontal: 22,
    paddingTop: 24,
    paddingBottom: 22,
    borderRadius: 28,
    overflow: 'hidden',
    shadowOffset: { width: 0, height: 18 },
    shadowOpacity: 0.26,
    shadowRadius: 36,
    elevation: 8,
  },
  heroHalo: {
    position: 'absolute',
    width: 150,
    height: 150,
    right: -52,
    top: -46,
    borderRadius: 75,
    backgroundColor: 'rgba(255, 255, 255, 0.16)',
  },
  resultStatus: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 11,
    paddingVertical: 7,
    borderRadius: 18,
    backgroundColor: 'rgba(255, 255, 255, 0.18)',
    marginBottom: 18,
  },
  resultStatusText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  scoreRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 10,
    marginBottom: 8,
  },
  score: {
    fontSize: 64,
    lineHeight: 66,
    fontWeight: '800',
    color: '#FFFFFF',
  },
  scoreUnit: {
    paddingBottom: 8,
    fontSize: 18,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  resultTitle: {
    fontSize: 20,
    lineHeight: 26,
    fontWeight: '800',
    color: '#FFFFFF',
    marginBottom: 7,
  },
  resultDesc: {
    fontSize: 13,
    lineHeight: 21,
    color: 'rgba(255, 255, 255, 0.9)',
  },
  heroAction: {
    alignSelf: 'flex-start',
    minHeight: 42,
    marginTop: 18,
    paddingHorizontal: 14,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.22)',
    backgroundColor: 'rgba(255, 255, 255, 0.18)',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  heroActionText: {
    fontSize: 13,
    fontWeight: '800',
    color: '#FFFFFF',
  },
  summaryGrid: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 14,
    marginBottom: 14,
  },
  summaryCard: {
    flex: 1,
    paddingHorizontal: 10,
    paddingVertical: 14,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#E8E8F0',
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
  },
  summaryValue: {
    fontSize: 18,
    fontWeight: '800',
    color: '#1A1A2E',
    marginBottom: 4,
  },
  summaryLabel: {
    fontSize: 11,
    fontWeight: '600',
    color: '#8A8A9A',
  },
  sectionCard: {
    padding: 18,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: '#E8E8F0',
    backgroundColor: '#FFFFFF',
    marginBottom: 14,
  },
  sectionHead: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#1A1A2E',
  },
  sectionLink: {
    fontSize: 12,
    fontWeight: '700',
    color: '#4F8EF7',
  },
  typeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 14,
  },
  typeName: {
    width: 72,
    fontSize: 13,
    fontWeight: '700',
    color: '#1A1A2E',
  },
  bar: {
    flex: 1,
    height: 8,
    borderRadius: 8,
    overflow: 'hidden',
    backgroundColor: '#F8F9FB',
  },
  barFill: {
    height: 8,
    borderRadius: 8,
  },
  typeScore: {
    width: 42,
    textAlign: 'right',
    fontSize: 12,
    fontWeight: '800',
    color: '#1A1A2E',
  },
  certificateCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    padding: 14,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(20, 201, 165, 0.18)',
    backgroundColor: 'rgba(20, 201, 165, 0.08)',
    marginBottom: 24,
  },
  certificateIcon: {
    width: 42,
    height: 42,
    borderRadius: 14,
    backgroundColor: '#14C9A5',
    alignItems: 'center',
    justifyContent: 'center',
  },
  failedCertificateIcon: {
    backgroundColor: '#FFB020',
  },
  certificateCopy: {
    flex: 1,
  },
  certificateTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: '#1A1A2E',
    marginBottom: 4,
  },
  certificateDesc: {
    fontSize: 12,
    lineHeight: 18,
    color: '#8A8A9A',
  },
  bottomBar: {
    paddingHorizontal: 20,
    paddingTop: 14,
    paddingBottom: 24,
    backgroundColor: '#FFFFFF',
    borderTopWidth: 1,
    borderTopColor: '#E8E8F0',
    flexDirection: 'row',
    gap: 12,
  },
  secondaryButton: {
    flex: 1,
    height: 52,
    borderRadius: 16,
    backgroundColor: '#F8F9FB',
    alignItems: 'center',
    justifyContent: 'center',
  },
  secondaryButtonText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#1A1A2E',
  },
  primaryButtonWrap: {
    flex: 1,
    height: 52,
    borderRadius: 16,
    shadowColor: '#4F8EF7',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.32,
    shadowRadius: 24,
    elevation: 6,
  },
  primaryButton: {
    flex: 1,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 6,
  },
  primaryButtonText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  homeIndicator: {
    height: 8,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  homeIndicatorBar: {
    width: 134,
    height: 5,
    borderRadius: 100,
    backgroundColor: '#C8C7CC',
  },
});

export default styles;
